/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-16 at 18:02:25 UTC 
 * Modify at your own risk.
 */

package com.example.entity.usereventlistendpoint.model;

/**
 * Model definition for UserEventList.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the usereventlistendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserEventList extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer hopNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userMail;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventKey() {
    return eventKey;
  }

  /**
   * @param eventKey eventKey or {@code null} for none
   */
  public UserEventList setEventKey(java.lang.String eventKey) {
    this.eventKey = eventKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHopNumber() {
    return hopNumber;
  }

  /**
   * @param hopNumber hopNumber or {@code null} for none
   */
  public UserEventList setHopNumber(java.lang.Integer hopNumber) {
    this.hopNumber = hopNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public UserEventList setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserMail() {
    return userMail;
  }

  /**
   * @param userMail userMail or {@code null} for none
   */
  public UserEventList setUserMail(java.lang.String userMail) {
    this.userMail = userMail;
    return this;
  }

  @Override
  public UserEventList set(String fieldName, Object value) {
    return (UserEventList) super.set(fieldName, value);
  }

  @Override
  public UserEventList clone() {
    return (UserEventList) super.clone();
  }

}
